/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-08-11 01:41:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import modeloVO.DatosPersonalesVO;
import modeloDAO.UsuarioDAO;
import modeloVO.UsuarioVO;
import java.util.ArrayList;
import modeloVO.ActividadCargadaVO;

public final class actualizarUsuarios_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/Componentes/Sessiones.jsp", Long.valueOf(1628614301237L));
    _jspx_dependants.put("/Componentes/header.jsp", Long.valueOf(1628614301256L));
    _jspx_dependants.put("/Componentes/head.jsp", Long.valueOf(1628614301253L));
    _jspx_dependants.put("/Componentes/datosUsuarioSesion.jsp", Long.valueOf(1628614301242L));
    _jspx_dependants.put("/Componentes/mensajesRespuesta.jsp", Long.valueOf(1628614301263L));
    _jspx_dependants.put("/Componentes/footer.jsp", Long.valueOf(1628614301249L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("modeloVO.ActividadCargadaVO");
    _jspx_imports_classes.add("modeloVO.UsuarioVO");
    _jspx_imports_classes.add("modeloVO.DatosPersonalesVO");
    _jspx_imports_classes.add("modeloDAO.UsuarioDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

response.setHeader("Pragma", "No-cache");
response.setHeader("Cache-control", "no-cache,no-store, must-revalidate");
response.setDateHeader("Expires", 0);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <h1>Hello World!</h1>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write('\n');
      out.write('\n');
      out.write('\n');

    String rol = "";
    Integer idusu = null;
    HttpSession miSesion = (HttpSession) request.getSession();
    
    
    if(miSesion.getAttribute("datosUsuario") == null ){
        request.getRequestDispatcher("login.jsp").forward(request, response);
    }else{
    
       
       
        
    }

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("      \n");
      out.write("        <title>Actualiza Usuario</title>\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        \n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"manifest\" href=\"site.webmanifest\">\n");
      out.write("        <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/slicknav.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/progressbar_barfiller.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/gijgo.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/animate.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/animated-headline.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/fontawesome-all.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/slick.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/style.css\">");
      out.write("\n");
      out.write("        \n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("  \n");
      out.write("<header>\n");
      out.write("            <div class=\"header-area\">\n");
      out.write("                <div class=\"main-header \">\n");
      out.write("                    <div class=\"header-top d-none d-sm-block\">\n");
      out.write("                        <div class=\"container-fluid\">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-xl-12\">\n");
      out.write("                                    <div class=\"d-flex justify-content-between flex-wrap align-items-center\">\n");
      out.write("                                        <div class=\"header-info-left\">\n");
      out.write("                                            <ul>     \n");
      out.write("                                                <li><i class=\"fas fa-map-marker-alt\"></i> Bogota Colombia</li>\n");
      out.write("                                                <li><i class=\"fas fa-phone-alt\"></i> 315 367 3692</li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"header-info-right\">\n");
      out.write("                                            <ul class=\"header-social\">    \n");
      out.write("                                                <li><a href=\"#\"><i class=\"fab fa-facebook\"></i></a></li>\n");
      out.write("                                                <li><a href=\"#\"><i class=\"fab fa-twitter\"></i></a></li>\n");
      out.write("                                                <li><a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a></li>\n");
      out.write("                                                <li> <a href=\"#\"><i class=\"fab fa-instagram\"></i></a></li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"header-bottom  header-sticky\">\n");
      out.write("                        <div class=\"container-fluid\">\n");
      out.write("                            <div class=\"row align-items-center\">\n");
      out.write("                                <!-- Logo -->\n");
      out.write("                                <div class=\"col-xl-2 col-lg-2\">\n");
      out.write("                                    <div class=\"logo\">\n");
      out.write("                                        <a href=\"index.jsp\"><img src=\"assets/img/logo/logo.png\" alt=\"\"></a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-xl-10 col-lg-10\">\n");
      out.write("                                    <!-- Main-menu -->\n");
      out.write("                                    <div class=\"main-menu f-right d-none d-lg-block\">\n");
      out.write("                                        <nav> \n");
      out.write("                                            <ul id=\"navigation\">   \n");
      out.write("                                                   <ul class=\"submenu\">\n");
      out.write("                                                       <li><p></p>\n");
      out.write("                                                       <li>\n");
      out.write("                                                           ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Componentes/cerrarSesion.jsp", out, true);
      out.write("\n");
      out.write("                                                       </li>\n");
      out.write("                                                    </ul>\n");
      out.write("                                                <a href=\"administrativo.jsp\"><h1>Administrativo</h1></a>\n");
      out.write("                                                <li><a href=\"#\">Matriculas</a>\n");
      out.write("                                                    <ul class=\"submenu\">\n");
      out.write("                                                        <li><a href=\"registrar_matricula.jsp\">Registrar matricula</a></li>\n");
      out.write("                                                        \n");
      out.write("                                                    </ul>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"#\">Docente</a>\n");
      out.write("                                                    <ul class=\"submenu\">\n");
      out.write("                                                        <li><a href=\"registrarDocente.jsp\">Registrar docente</a></li>\n");
      out.write("                                                        <li><a href=\"listardocentes.jsp\">Ver docentes</a></li>\n");
      out.write("                                                    </ul>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"#\">Estudiante</a>\n");
      out.write("                                                    <ul class=\"submenu\">\n");
      out.write("                                                        <li><a href=\"registrarDocente.jsp\">Registrar estudiantes</a></li>\n");
      out.write("                                                        <li><a href=\"listarEstudiantes.jsp\">Ver estudiantes</a></li>\n");
      out.write("                                                    </ul>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"#\">Mensajes</a>\n");
      out.write("                                                    <ul class=\"submenu\">\n");
      out.write("                                                        <li><a href=\"crearmensaje.jsp\">Crear y listar mensajes</a></li>\n");
      out.write("                                                        \n");
      out.write("                                                    </ul>\n");
      out.write("                                                </li>    \n");
      out.write("                                                \n");
      out.write("                                                 <li><a href=\"#\">Cerrar Sesion</a>\n");
      out.write("                                                    <ul class=\"submenu\">\n");
      out.write("                                                        <li><a href=\"login.jsp\">Cerrar Sesion</a></li>\n");
      out.write("                                                       \n");
      out.write("                                                    </ul>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </nav>\n");
      out.write("                                    </div>\n");
      out.write("                                </div> \n");
      out.write("                                <!-- Mobile Menu -->\n");
      out.write("                                <div class=\"col-12\">\n");
      out.write("                                    <div class=\"mobile_menu d-block d-lg-none\"></div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Header End -->\n");
      out.write("        </header>\n");
      out.write("                                                       \n");
      out.write("                                                       \n");
      out.write("                                                       \n");
      out.write("                                                       ");
      out.write("\n");
      out.write("         <section class=\"container-fluid\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-xl-12\">\n");
      out.write("                    <div class=\"registrodocente\">\n");
      out.write("                        <h1>Actualizar Usuario</h1>                                          \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-xl-4\">\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-xl-4\">\n");
      out.write("\n");
      out.write("                    <div class=\"datospersonales\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                      \n");
      out.write("\n");
      out.write("                        <form class=\"container\" action=\"Usuario\" method=\"post\" >       \n");
      out.write("                                \n");
      out.write("                            \n");
      out.write("                            ");
 
                               int idDatos = 0;
                               String datosnombres="", datosapellidos="",datostelefono="", datosemail="";
            
            
             
                                    if(request.getAttribute("idDatos")!= null){
                                    idDatos =(int) request.getAttribute("idDatos");
                                       
                                    }
                                    
                                    if(request.getAttribute("datosnombres")!= null){
                                         datosnombres =(String) request.getAttribute("datosnombres");
                                    }
                                    
                                     if(request.getAttribute("datosapellidos")!= null){
                                         datosapellidos =(String) request.getAttribute("datosapellidos");
                                    }
                                    
                                      if(request.getAttribute("datostelefono")!= null){
                                         datostelefono =(String) request.getAttribute("datostelefono");
                                    }
                                      if(request.getAttribute("datosemail")!= null){
                                         datosemail =(String) request.getAttribute("datosemail");
                                    }
                                    ;
      out.write("\n");
      out.write("                              \n");
      out.write("\n");
      out.write("                              \n");
      out.write(" \n");
      out.write("                                    \n");
      out.write("                           \n");
      out.write("                                               <label for=\"numeroDocumento\">Numero Documento *</label>\n");
      out.write("                                               <input type=\"text\"  name=\"textnumeroid\" value=\"");
      out.print(idDatos);
      out.write("\">\n");
      out.write("                                            <br></br>\n");
      out.write("                                            <select class=\"tipodoc\" name=\"texttipoid\">\n");
      out.write("                                    <option>Seleccione...</option>\n");
      out.write("                                    <option value=\"Registro civil\">RC</option>\n");
      out.write("                                    <option value=\"Tarjeta de identidad\">TI</option>\n");
      out.write("                                    <option value=\"Cedula de ciudadania\">CC</option>\n");
      out.write("                                </select><br><br>\n");
      out.write("                                              \n");
      out.write("                                                    <label >Nombres *</label>\n");
      out.write("                                                    <input type=\"text\"  name=\"textnombres\" value=\"");
      out.print(datosnombres);
      out.write("\">\n");
      out.write("                                              \n");
      out.write("                                                <br></br>\n");
      out.write("                                          \n");
      out.write("                                             \n");
      out.write("                                                    <label for=\"apellidos\">Apellidos *</label>\n");
      out.write("                                                <input type=\"text\"  name=\"textapellidos\" value=\"");
      out.print(datosapellidos);
      out.write("\">\n");
      out.write("                                               <br></br>\n");
      out.write("                                          \n");
      out.write("                                                 <br></br>\n");
      out.write("                                          \n");
      out.write("                                                      <label >Telefono *</label>\n");
      out.write("                                                <input type=\"text\"  name=\"texttelefono\" value=\"");
      out.print(datostelefono);
      out.write("\">\n");
      out.write("                                                 <br></br\n");
      out.write("                                                   <label >Email *</label>\n");
      out.write("                                                <input type=\"email\"  name=\"textemail\" value=\"");
      out.print(datosemail);
      out.write("\">\n");
      out.write("                                                 \n");
      out.write("                                           <br></br>\n");
      out.write("                                    <input value=\"7\" name=\"opcion\" type=\"hidden\">\n");
      out.write("                                 \n");
      out.write("                                <input type=\"submit\" value=\"Actualizar Usuario\"  id=\"btn\" class=\"btn\"/>\n");
      out.write("                              \n");
      out.write("                            \n");
      out.write("                            \n");
      out.write("                                     \n");
      out.write("                                  \n");
      out.write("                             \n");
      out.write("                          \n");
      out.write("                        </form>\n");
      out.write("                \n");
      out.write("                                ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div style=\"color: #007180;\">\n");
      out.write("                        ");

                            if (request.getAttribute("mensajeError") != null) {
                        
      out.write("\n");
      out.write("                        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mensajeError}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                        ");
} else {
      out.write("\n");
      out.write("                        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mensajeExito}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                        ");
}
      out.write("\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("               \n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        </section>\n");
      out.write("          ");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<footer>\n");
      out.write("            <div class=\"footer-wrappper footer-bg\">\n");
      out.write("                <!-- Footer Start-->\n");
      out.write("                <div class=\"footer-area footer-padding\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <div class=\"row justify-content-between\">\n");
      out.write("                            <div class=\"col-xl-5 col-lg-6 col-md-6 col-sm-8\">\n");
      out.write("                                <div class=\"single-footer-caption mb-50\">\n");
      out.write("                                    <div class=\"single-footer-caption mb-30\">\n");
      out.write("                                        <!-- logo -->\n");
      out.write("                                        <div class=\"footer-logo mb-25\">\n");
      out.write("                                            <a href=\"index.html\"><img src=\"assets/img/logo/logo2_footer.png\" alt=\"\"></a>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"footer-tittle\">\n");
      out.write("                                            <div class=\"footer-pera\">\n");
      out.write("                                                <p>Nuestro objetivo enseñar de la mejor forma con estándar de calidad</p>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <!-- social -->\n");
      out.write("                                        <div class=\"footer-social\">\n");
      out.write("                                            <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\n");
      out.write("                                            <a href=\"https://bit.ly/sai4ull\"><i class=\"fab fa-facebook-f\"></i></a>\n");
      out.write("                                            <a href=\"#\"><i class=\"fab fa-pinterest-p\"></i></a>\n");
      out.write("                                            <a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-xl-2 col-lg-3 col-md-3 col-sm-4\">\n");
      out.write("                                <div class=\"single-footer-caption mb-50\">\n");
      out.write("                                    <div class=\"footer-tittle\">\n");
      out.write("                                        <h4>Enlaces rapidos </h4>\n");
      out.write("                                        <ul>\n");
      out.write("                                            <li><a href=\"#\">Clases</a></li>\n");
      out.write("                                            <li><a href=\"#\">Join with us</a></li>\n");
      out.write("                                            <li><a href=\"#\">Sobre Nosotros</a></li>\n");
      out.write("                                            <li><a href=\"#\">Blog</a></li>\n");
      out.write("                                            <li><a href=\"#\">Eventos</a></li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-xl-2 col-lg-3 col-md-3 col-sm-6\">\n");
      out.write("                                <div class=\"single-footer-caption mb-50\">\n");
      out.write("                                    <div class=\"footer-tittle\">\n");
      out.write("                                        <h4>Sobre Nosotros</h4>\n");
      out.write("                                        <ul>\n");
      out.write("                                            <li><a href=\"#\">Nuestro Equipo</a></li>\n");
      out.write("                                            <li><a href=\"#\">Politicas De Privacidad</a></li>\n");
      out.write("                                            <li><a href=\"#\">Testimonios</a></li>\n");
      out.write("                                            <li><a href=\"#\">Programas</a></li>\n");
      out.write("                                            <li><a href=\"#\">Nuestras historias</a></li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- footer-bottom area -->\n");
      out.write("                <div class=\"footer-bottom-area\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <div class=\"footer-border\">\n");
      out.write("                            <div class=\"row d-flex align-items-center\">\n");
      out.write("                                <div class=\"col-xl-12 \">\n");
      out.write("                                    <div class=\"footer-copy-right text-center\">\n");
      out.write("                                        <p>Copyright &copy;<script>document.write(new Date().getFullYear());</script> Elaborado por | \n");
      out.write("                                        </p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- Footer End-->\n");
      out.write("            </div>\n");
      out.write("        </footer>");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
