/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-08-11 01:03:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Componentes/head.jsp", Long.valueOf(1628614301253L));
    _jspx_dependants.put("/Componentes/footer.jsp", Long.valueOf(1628614301249L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("        <title>Educacion</title>\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <link rel=\"manifest\" href=\"site.webmanifest\">\n");
      out.write("        <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\n");
      out.write("\n");
      out.write("        <!-- CSS here -->\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"manifest\" href=\"site.webmanifest\">\n");
      out.write("        <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/slicknav.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/progressbar_barfiller.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/gijgo.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/animate.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/animated-headline.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/fontawesome-all.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/slick.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/style.css\">");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <!-- ? Preloader Start -->\n");
      out.write("        <div id=\"preloader-active\">\n");
      out.write("            <div class=\"preloader d-flex align-items-center justify-content-center\">\n");
      out.write("                <div class=\"preloader-inner position-relative\">\n");
      out.write("                    <div class=\"preloader-circle\"></div>\n");
      out.write("                    <div class=\"preloader-img pere-text\">\n");
      out.write("                        <img src=\"assets/img/logo/loder.png\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Preloader Start -->\n");
      out.write("        <header>\n");
      out.write("            <!-- Header Start -->\n");
      out.write("            <div class=\"header-area\">\n");
      out.write("                <div class=\"main-header \">\n");
      out.write("                    <div class=\"header-top d-none d-sm-block\">\n");
      out.write("                        <div class=\"container-fluid\">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-xl-12\">\n");
      out.write("                                    <div class=\"d-flex justify-content-between flex-wrap align-items-center\">\n");
      out.write("                                        <div class=\"header-info-left\">\n");
      out.write("                                            <ul>     \n");
      out.write("                                                <li><i class=\"fas fa-map-marker-alt\"></i> Bogota Colombia</li>\n");
      out.write("                                                <li><i class=\"fas fa-phone-alt\"></i> 315 367 3692</li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"header-info-right\">\n");
      out.write("                                            <ul class=\"header-social\">    \n");
      out.write("                                                <li><a href=\"#\"><i class=\"fab fa-facebook\"></i></a></li>\n");
      out.write("                                                <li><a href=\"#\"><i class=\"fab fa-twitter\"></i></a></li>\n");
      out.write("                                                <li><a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a></li>\n");
      out.write("                                                <li> <a href=\"#\"><i class=\"fab fa-instagram\"></i></a></li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"header-bottom  header-sticky\">\n");
      out.write("                        <div class=\"container-fluid\">\n");
      out.write("                            <div class=\"row align-items-center\">\n");
      out.write("                                <!-- Logo -->\n");
      out.write("                                <div class=\"col-xl-2 col-lg-2\">\n");
      out.write("                                    <div class=\"logo\">\n");
      out.write("                                        <a href=\"index.html\"><img src=\"assets/img/logo/logo.png\" alt=\"\"></a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-xl-10 col-lg-10\">\n");
      out.write("                                    <!-- Main-menu -->\n");
      out.write("                                    <div class=\"main-menu f-right d-none d-lg-block\">\n");
      out.write("                                        <nav> \n");
      out.write("                                            <ul id=\"navigation\">                                                                                                                                     \n");
      out.write("                                                <li><a href=\"index.jsp\">Inicio</a></li>\n");
      out.write("                                                <li><a href=\"class.jsp\">Clases</a></li>\n");
      out.write("                                                <li><a href=\"about.jsp\">Acerca de</a></li>\n");
      out.write("                                                <li><a href=\"blog.jsp\">Blog</a>\n");
      out.write("                                                    <ul class=\"submenu\">\n");
      out.write("                                                        <li><a href=\"blog.jsp\">Blog</a></li>\n");
      out.write("                                                        <li><a href=\"blog_details.jsp\">Detalles del blog</a></li>\n");
      out.write("                                                        <li><a href=\"elements.jsp\">Elementos</a></li>\n");
      out.write("                                                    </ul>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"contact.jsp\">Contacto</a></li>\n");
      out.write("                                                <li>\n");
      out.write("                                                    <div class=\"header-right-btn f-right  ml-15\">\n");
      out.write("                                                        <a href=\"login.jsp\" class=\"header-btn\">Iniciar Sesión</a>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </nav>\n");
      out.write("                                    </div>\n");
      out.write("                                </div> \n");
      out.write("                                <!-- Mobile Menu -->\n");
      out.write("                                <div class=\"col-12\">\n");
      out.write("                                    <div class=\"mobile_menu d-block d-lg-none\"></div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Header End -->\n");
      out.write("        </header>\n");
      out.write("        <main>\n");
      out.write("            <!--? slider Area Start-->\n");
      out.write("            <section class=\"slider-area \">\n");
      out.write("                <div class=\"slider-active\">\n");
      out.write("                    <!-- Single Slider -->\n");
      out.write("                    <div class=\"single-slider slider-height d-flex align-items-center\">\n");
      out.write("                        <div class=\"container\">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-xl-6 col-lg-7 col-md-10 col-sm-11\">\n");
      out.write("                                    <div class=\"hero__caption\">\n");
      out.write("                                        <h1 data-animation=\"fadeInLeft\" data-delay=\"0.2s\">Aprendizaje de<br> Calidad</h1>\n");
      out.write("                                        <span data-animation=\"fadeInLeft\" data-delay=\"0.4s\">Para cada niño</span>\n");
      out.write("                                        <a href=\"#\" class=\"btn hero-btn\" data-animation=\"fadeInLeft\" data-delay=\"0.7s\">Explorar clases</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>          \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("            <!-- End Slider -->\n");
      out.write("            <!--? About Area Start -->\n");
      out.write("            <div class=\"about-low-area section-padding40\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row justify-content-center\">\n");
      out.write("                        <div class=\"col-xl-10 col-lg-10 col-md-10 col-sm-11\">\n");
      out.write("                            <div class=\"section-tittle text-center mb-70\">\n");
      out.write("                                <h2>Bienvenidos a nuestro  <span>jardín infantil</span></h2>\n");
      out.write("                                <p>\n");
      out.write("                                    ¡Nuestras matrículas están abiertas!\n");
      out.write("\n");
      out.write("                                    Conoce los pasos para ser parte de\n");
      out.write("                                    nuestra comunidad Santanista, escríbenos.</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"row align-items-center\">\n");
      out.write("                        <div class=\"col-lg-5 col-md-12\">\n");
      out.write("                            <div class=\"about-caption\">\n");
      out.write("                                <div class=\"single-features mb-30\">\n");
      out.write("                                    <div class=\"features-icon\">\n");
      out.write("                                        <img src=\"assets/img/icon/about-icon1.svg\" alt=\"\">\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"features-caption\">\n");
      out.write("                                        <h3 class=\"color-font1\">Deportes inter escolares</h3>\n");
      out.write("                                        <p>Las palabras que usa en su comunicación escrita lo dicen todo.</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"single-features mb-30\">\n");
      out.write("                                    <div class=\"features-icon\">\n");
      out.write("                                        <img src=\"assets/img/icon/about-icon2.svg\" alt=\"\">\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"features-caption\">\n");
      out.write("                                        <h3 class=\"color-font2\">Ambiente amigable</h3>\n");
      out.write("                                        <p>Las palabras que usa en su comunicación escrita lo dicen todo.</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"single-features mb-30\">\n");
      out.write("                                    <div class=\"features-icon\">\n");
      out.write("                                        <img src=\"assets/img/icon/about-icon3.svg\" alt=\"\">\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"features-caption\">\n");
      out.write("                                        <h3 class=\"color-font3\">\n");
      out.write("                                            Clase multimedia</h3>\n");
      out.write("                                        <p>Las palabras que usa en su comunicación escrita lo dicen todo.</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-lg-7 col-md-12\">\n");
      out.write("                            <!-- about-img -->\n");
      out.write("                            <div class=\"about-img \">\n");
      out.write("                                <img src=\"assets/img/gallery/about2.png\" alt=\"\" class=\"w-100\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- About Area End -->\n");
      out.write("            <!--? Class-offer-area Start -->\n");
      out.write("            <div class=\"class-offer-area section-bg2 section-padding40 \" data-background=\"assets/img/gallery/section_bg1.png\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row justify-content-center\">\n");
      out.write("                        <div class=\"col-lg-8 col-md-10 col-sm-11\">\n");
      out.write("                            <!-- Section Tittle -->\n");
      out.write("                            <div class=\"section-tittle text-center mb-80\">\n");
      out.write("                                <h2>\n");
      out.write("Clases que ofrecemos</h2>\n");
      out.write("                                <p>Somos un jardín infantil moderno, con un modelo pedagógico a la vanguardia, que forma buenos? seres humanos, felices y con criterio para enfrentarse al mundo.</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"class-offer-active\">\n");
      out.write("                        <div class=\"col-lg-4 col-md-6 col-sm-6\">\n");
      out.write("                            <!-- Single -->\n");
      out.write("                            <div class=\"properties pb-30\">\n");
      out.write("                                <div class=\"properties__card\">\n");
      out.write("                                    <div class=\"properties__img\">\n");
      out.write("                                        <a href=\"#\"><img src=\"assets/img/gallery/class-img1.png\" alt=\"\"></a>\n");
      out.write("                                        <div class=\"img-text\">\n");
      out.write("                                            <span class=\"open\">Admisión cerrada</span>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"properties__caption\">\n");
      out.write("                                        <h3><a href=\"#\">\n");
      out.write("Desafío inteligente</a></h3>\n");
      out.write("                                        <p>Las palabras que usa en su comunicación escrita lo dicen todo.</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"properties__footer d-flex justify-content-between align-items-center\">\n");
      out.write("                                        <div class=\"class-day\">\n");
      out.write("                                            <span class=\"color-font4\">3-5</span>\n");
      out.write("                                            <p>Grupo de edades</p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"class-day\">\n");
      out.write("                                            <span class=\"color-font2\">30</span>\n");
      out.write("                                            <p>Clases</p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"class-day\">\n");
      out.write("                                            <span class=\"color-font1\">10/h</span>\n");
      out.write("                                            <p>Precio de la clase</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-lg-4 col-md-6 col-sm-6\">\n");
      out.write("                            <!-- Single -->\n");
      out.write("                            <div class=\"properties pb-30\">\n");
      out.write("                                <div class=\"properties__card\">\n");
      out.write("                                    <div class=\"properties__img\">\n");
      out.write("                                        <a href=\"#\"><img src=\"assets/img/gallery/class-img2.png\" alt=\"\"></a>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"properties__caption\">\n");
      out.write("                                        <h3><a href=\"#\">Desafío inteligente</a></h3>\n");
      out.write("                                        <p>Las palabras que usa en su comunicación escrita lo dicen todo.</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"properties__footer d-flex justify-content-between align-items-center\">\n");
      out.write("                                        <div class=\"class-day\">\n");
      out.write("                                            <span class=\"color-font4\">3-5</span>\n");
      out.write("                                            <p>Grupo de edades</p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"class-day\">\n");
      out.write("                                            <span class=\"color-font2\">30</span>\n");
      out.write("                                            <p>Clases</p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"class-day\">\n");
      out.write("                                            <span class=\"color-font1\">10/h</span>\n");
      out.write("                                            <p>Precio de clase</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-lg-4 col-md-6 col-sm-6\">\n");
      out.write("                            <!-- Single -->\n");
      out.write("                            \n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-lg-4 col-md-6 col-sm-6\">\n");
      out.write("                            <!-- Single -->\n");
      out.write("                            <div class=\"properties pb-30\">\n");
      out.write("                                <div class=\"properties__card\">\n");
      out.write("                                    <div class=\"properties__img\">\n");
      out.write("                                        <a href=\"#\"><img src=\"assets/img/gallery/class-img2.png\" alt=\"\"></a>\n");
      out.write("                                        <div class=\"img-text\">\n");
      out.write("                                            <span class=\"open\">Admission Closed</span>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"properties__caption\">\n");
      out.write("                                        <h3><a href=\"#\">Pinta y Pinta </a></h3>\n");
      out.write("                                        <p>Las palabras que usa en su comunicación escrita lo dicen todo.</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"properties__footer d-flex justify-content-between align-items-center\">\n");
      out.write("                                        <div class=\"class-day\">\n");
      out.write("                                            <span class=\"color-font4\">3-5</span>\n");
      out.write("                                            <p>Grupo de edades</p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"class-day\">\n");
      out.write("                                            <span class=\"color-font2\">30</span>\n");
      out.write("                                            <p>Clases</p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"class-day\">\n");
      out.write("                                            <span class=\"color-font1\">20/h</span>\n");
      out.write("                                            <p>Precio por clase</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-lg-12\">\n");
      out.write("                            <div class=\"browse-all text-center mt-30\">\n");
      out.write("                                <a href=\"#\" class=\"border-btn\">Mas clases</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Class-offer-area End -->\n");
      out.write("            <!--? Date Count Start -->\n");
      out.write("            <div class=\"date-events section-bg2 section-padding40\" data-background=\"assets/img/gallery/section_bg2.png\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row justify-content-center\">\n");
      out.write("                        <div class=\"col-lg-6 col-md-9\">\n");
      out.write("                            <div class=\"date-wrapper\">\n");
      out.write("                                <div class=\"section-tittle text-center mb-30\">\n");
      out.write("                                    <span class=\"span\">28 septiembre 2021</span>\n");
      out.write("                                    <h2>Evento de dibujo</h2>\n");
      out.write("                                    <p>Cada evento tiene asociado un cuadro. Es el que el artista explicará ese día. ¡Escoge el que más te guste!ourth.</p>\n");
      out.write("                                    <a href=\"#\" class=\"btn mt-10\">Ver evento</a>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- Timer -->\n");
      out.write("                                <div class=\"cd-timer\" id=\"countdown\">\n");
      out.write("                                    <div class=\"cd-item\">\n");
      out.write("                                        <span>40</span>\n");
      out.write("                                        <p>Dias</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"cd-item\">\n");
      out.write("                                        <span>18</span>\n");
      out.write("                                        <p>Horas</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"cd-item\">\n");
      out.write("                                        <span>46</span>\n");
      out.write("                                        <p>Minutos</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"cd-item\">\n");
      out.write("                                        <span>32</span>\n");
      out.write("                                        <p>Segundos</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- /End -->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Date Count End -->\n");
      out.write("            <!--? Team Ara Start -->\n");
      out.write("            <div class=\"team-area section-padding\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row justify-content-center\">\n");
      out.write("                        <div class=\"cl-xl-8 col-lg-8 col-md-10\">\n");
      out.write("                            <!-- Section Tittle -->\n");
      out.write("                            <div class=\"section-tittle text-center mb-60\">\n");
      out.write("                                <h2>Profesores expertos</h2>\n");
      out.write("                                <p>IEBS cuenta con un claustro de profesores altamente cualificado\n");
      out.write("\n");
      out.write("En ABCEDUCANDO pensamos que para poder enseñar te debe apasionar lo que haces. Porque enseñar es la capacidad de emocionar a nuestros alumnos para que se sientan motivados con lo que aprenden y el esfuerzo que requiere aprender sea mucho más fácil de llevar y porque no divertido.</p>\n");
      out.write("                            </div> \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"c-row\">\n");
      out.write("                        <div class=\"team-active\">\n");
      out.write("                            <div class=\"col-lg-3 col-md-4 col-sm-6\">\n");
      out.write("                                <div class=\"single-team mb-30 text-center\">\n");
      out.write("                                    <div class=\"team-img\">\n");
      out.write("                                        <img src=\"assets/img/gallery/team1.png\" alt=\"\">\n");
      out.write("                                        <div class=\"team-caption\">\n");
      out.write("                                            <!-- Blog Social -->\n");
      out.write("                                            <div class=\"team-social\">\n");
      out.write("                                                <ul>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fab fa-facebook\"></i></a></li>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fab fa-twitter\"></i></a></li>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a></li>\n");
      out.write("                                                    <li> <a href=\"#\"><i class=\"fab fa-instagram\"></i></a></li>\n");
      out.write("                                                </ul>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"team-info\">\n");
      out.write("                                        <h3><a href=\"#\">Mr. Robin</a></h3>\n");
      out.write("                                        <p> Instructor De deportes</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-lg-3 col-md-4 col-sm-6\">\n");
      out.write("                                <div class=\"single-team mb-30 text-center\">\n");
      out.write("                                    <div class=\"team-img\">\n");
      out.write("                                        <img src=\"assets/img/gallery/team2.png\" alt=\"\">\n");
      out.write("                                        <div class=\"team-caption\">\n");
      out.write("                                            <!-- Blog Social -->\n");
      out.write("                                            <div class=\"team-social\">\n");
      out.write("                                                <ul>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fab fa-facebook\"></i></a></li>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fab fa-twitter\"></i></a></li>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a></li>\n");
      out.write("                                                    <li> <a href=\"#\"><i class=\"fab fa-instagram\"></i></a></li>\n");
      out.write("                                                </ul>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"team-info\">\n");
      out.write("                                        <h3><a href=\"#\">Carlos</a></h3>\n");
      out.write("                                        <p>Instructor De deportes </p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-lg-3 col-md-4 col-sm-6\">\n");
      out.write("                                <div class=\"single-team mb-30 text-center\">\n");
      out.write("                                    <div class=\"team-img\">\n");
      out.write("                                        <img src=\"assets/img/gallery/team3.png\" alt=\"\">\n");
      out.write("                                        <div class=\"team-caption\">\n");
      out.write("                                            <!-- Blog Social -->\n");
      out.write("                                            <div class=\"team-social\">\n");
      out.write("                                                <ul>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fab fa-facebook\"></i></a></li>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fab fa-twitter\"></i></a></li>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a></li>\n");
      out.write("                                                    <li> <a href=\"#\"><i class=\"fab fa-instagram\"></i></a></li>\n");
      out.write("                                                </ul>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"team-info\">\n");
      out.write("                                        <h3><a href=\"#\">Richard</a></h3>\n");
      out.write("                                        <p>Instructor De pintura</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-lg-3 col-md-4 col-sm-6\">\n");
      out.write("                                <div class=\"single-team mb-30 text-center\">\n");
      out.write("                                    <div class=\"team-img\">\n");
      out.write("                                        <img src=\"assets/img/gallery/team2.png\" alt=\"\">\n");
      out.write("                                        <div class=\"team-caption\">\n");
      out.write("                                            <!-- Blog Social -->\n");
      out.write("                                            <div class=\"team-social\">\n");
      out.write("                                                <ul>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fab fa-facebook\"></i></a></li>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fab fa-twitter\"></i></a></li>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a></li>\n");
      out.write("                                                    <li> <a href=\"#\"><i class=\"fab fa-instagram\"></i></a></li>\n");
      out.write("                                                </ul>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"team-info\">\n");
      out.write("                                        <h3><a href=\"#\">Amilia</a></h3>\n");
      out.write("                                        <p>Profesora de musica</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-lg-3 col-md-4 col-sm-6\">\n");
      out.write("                                <div class=\"single-team mb-30 text-center\">\n");
      out.write("                                    <div class=\"team-img\">\n");
      out.write("                                        <img src=\"assets/img/gallery/team3.png\" alt=\"\">\n");
      out.write("                                        <div class=\"team-caption\">\n");
      out.write("                                            <!-- Blog Social -->\n");
      out.write("                                            <div class=\"team-social\">\n");
      out.write("                                                <ul>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fab fa-facebook\"></i></a></li>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fab fa-twitter\"></i></a></li>\n");
      out.write("                                                    <li><a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a></li>\n");
      out.write("                                                    <li> <a href=\"#\"><i class=\"fab fa-instagram\"></i></a></li>\n");
      out.write("                                                </ul>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"team-info\">\n");
      out.write("                                        <h3><a href=\"#\">Mr. Jacson Clay</a></h3>\n");
      out.write("                                        <p>Instructor Pintura</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Team Ara End -->\n");
      out.write("            <!--? Testimonial Start -->\n");
      out.write("            <div class=\"testimonial-area testimonial-padding section-bg2\" data-background=\"assets/img/gallery/section_bg3.png\">\n");
      out.write("                <div class=\"container \">\n");
      out.write("                    <div class=\"row d-flex justify-content-center\">\n");
      out.write("                        <div class=\"col-xl-11 col-lg-11 col-md-9\">\n");
      out.write("                            <div class=\"h1-testimonial-active\">\n");
      out.write("                                <!-- Single Testimonial -->\n");
      out.write("                                <div class=\"single-testimonial text-center\">\n");
      out.write("                                    <div class=\"testimonial-caption \">\n");
      out.write("                                        <div class=\"testimonial-top-cap\">\n");
      out.write("                                            <img src=\"assets/img/gallery/testimonial.png\" alt=\"\">\n");
      out.write("                                            <p>Desde el momento de su matriculación, el alumno pasará a formar parte de la Comunidad de ABCEDUCANDO, un punto de encuentro entre alumnos y profesores que fomenta la interactividad, la comunicación y el networking entre profesionales. Estos son algunos de los servicios que ofrecemos a nuestros alumnos</p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <!-- founder -->\n");
      out.write("                                        <div class=\"testimonial-founder d-flex align-items-center justify-content-center\">\n");
      out.write("                                            <div class=\"founder-img\">\n");
      out.write("                                                <img src=\"assets/img/gallery/founder-img.svg\" alt=\"\">\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"founder-text\">\n");
      out.write("                                                <span>Jacson Miller</span>\n");
      out.write("                                                <p>Diseñador Grafico</p>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- Single Testimonial -->\n");
      out.write("                                <div class=\"single-testimonial text-center\">\n");
      out.write("                                    <div class=\"testimonial-caption \">\n");
      out.write("                                        <div class=\"testimonial-top-cap\">\n");
      out.write("                                            <img src=\"assets/img/gallery/testimonial.png\" alt=\"\">\n");
      out.write("                                            <p></p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <!-- founder -->\n");
      out.write("                                        <div class=\"testimonial-founder d-flex align-items-center justify-content-center\">\n");
      out.write("                                            <div class=\"founder-img\">\n");
      out.write("                                                <img src=\"assets/img/gallery/founder-img.svg\" alt=\"\">\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"founder-text\">\n");
      out.write("                                                <span>Jacson Miller</span>\n");
      out.write("                                                <p>Designer @Colorlib</p>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Testimonial End -->\n");
      out.write("            <!--? instagram-social start -->\n");
      out.write("            <div class=\"instagram-area fix\">\n");
      out.write("                <div class=\"container-fluid p-0\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-xl-12\">\n");
      out.write("                            <div class=\"instagram-active owl-carousel\">\n");
      out.write("                                <div class=\"single-instagram\">\n");
      out.write("                                    <img src=\"assets/img/gallery/instra1.png\" alt=\"\">\n");
      out.write("                                    <a href=\"#\"><i class=\"ti-instagram\"></i></a>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"single-instagram\">\n");
      out.write("                                    <img src=\"assets/img/gallery/instra2.png\" alt=\"\">\n");
      out.write("                                    <a href=\"#\"><i class=\"ti-instagram\"></i></a>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"single-instagram\">\n");
      out.write("                                    <img src=\"assets/img/gallery/instra3.png\" alt=\"\">\n");
      out.write("                                    <a href=\"#\"><i class=\"ti-instagram\"></i></a>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"single-instagram\">\n");
      out.write("                                    <img src=\"assets/img/gallery/instra4.png\" alt=\"\">\n");
      out.write("                                    <a href=\"#\"><i class=\"ti-instagram\"></i></a>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"single-instagram\">\n");
      out.write("                                    <img src=\"assets/img/gallery/instra1.png\" alt=\"\">\n");
      out.write("                                    <a href=\"#\"><i class=\"ti-instagram\"></i></a>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"single-instagram\">\n");
      out.write("                                    <img src=\"assets/img/gallery/instra4.png\" alt=\"\">\n");
      out.write("                                    <a href=\"#\"><i class=\"ti-instagram\"></i></a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- instagram-social End -->\n");
      out.write("        </main>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<footer>\n");
      out.write("            <div class=\"footer-wrappper footer-bg\">\n");
      out.write("                <!-- Footer Start-->\n");
      out.write("                <div class=\"footer-area footer-padding\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <div class=\"row justify-content-between\">\n");
      out.write("                            <div class=\"col-xl-5 col-lg-6 col-md-6 col-sm-8\">\n");
      out.write("                                <div class=\"single-footer-caption mb-50\">\n");
      out.write("                                    <div class=\"single-footer-caption mb-30\">\n");
      out.write("                                        <!-- logo -->\n");
      out.write("                                        <div class=\"footer-logo mb-25\">\n");
      out.write("                                            <a href=\"index.html\"><img src=\"assets/img/logo/logo2_footer.png\" alt=\"\"></a>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"footer-tittle\">\n");
      out.write("                                            <div class=\"footer-pera\">\n");
      out.write("                                                <p>Nuestro objetivo enseñar de la mejor forma con estándar de calidad</p>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <!-- social -->\n");
      out.write("                                        <div class=\"footer-social\">\n");
      out.write("                                            <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\n");
      out.write("                                            <a href=\"https://bit.ly/sai4ull\"><i class=\"fab fa-facebook-f\"></i></a>\n");
      out.write("                                            <a href=\"#\"><i class=\"fab fa-pinterest-p\"></i></a>\n");
      out.write("                                            <a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-xl-2 col-lg-3 col-md-3 col-sm-4\">\n");
      out.write("                                <div class=\"single-footer-caption mb-50\">\n");
      out.write("                                    <div class=\"footer-tittle\">\n");
      out.write("                                        <h4>Enlaces rapidos </h4>\n");
      out.write("                                        <ul>\n");
      out.write("                                            <li><a href=\"#\">Clases</a></li>\n");
      out.write("                                            <li><a href=\"#\">Join with us</a></li>\n");
      out.write("                                            <li><a href=\"#\">Sobre Nosotros</a></li>\n");
      out.write("                                            <li><a href=\"#\">Blog</a></li>\n");
      out.write("                                            <li><a href=\"#\">Eventos</a></li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-xl-2 col-lg-3 col-md-3 col-sm-6\">\n");
      out.write("                                <div class=\"single-footer-caption mb-50\">\n");
      out.write("                                    <div class=\"footer-tittle\">\n");
      out.write("                                        <h4>Sobre Nosotros</h4>\n");
      out.write("                                        <ul>\n");
      out.write("                                            <li><a href=\"#\">Nuestro Equipo</a></li>\n");
      out.write("                                            <li><a href=\"#\">Politicas De Privacidad</a></li>\n");
      out.write("                                            <li><a href=\"#\">Testimonios</a></li>\n");
      out.write("                                            <li><a href=\"#\">Programas</a></li>\n");
      out.write("                                            <li><a href=\"#\">Nuestras historias</a></li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- footer-bottom area -->\n");
      out.write("                <div class=\"footer-bottom-area\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <div class=\"footer-border\">\n");
      out.write("                            <div class=\"row d-flex align-items-center\">\n");
      out.write("                                <div class=\"col-xl-12 \">\n");
      out.write("                                    <div class=\"footer-copy-right text-center\">\n");
      out.write("                                        <p>Copyright &copy;<script>document.write(new Date().getFullYear());</script> Elaborado por | \n");
      out.write("                                        </p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- Footer End-->\n");
      out.write("            </div>\n");
      out.write("        </footer>");
      out.write("\n");
      out.write("        <!-- Scroll Up -->\n");
      out.write("        <div id=\"back-top\" >\n");
      out.write("            <a title=\"Go to Top\" href=\"#\"> <i class=\"fas fa-level-up-alt\"></i></a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- JS here -->\n");
      out.write("        <!--Popper, Bootstrap -->\n");
      out.write("        <script src=\"./assets/js/vendor/modernizr-3.5.0.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/vendor/jquery-1.12.4.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/popper.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("        <!-- Jquery Slick , Owl-Carousel Plugins -->\n");
      out.write("        <script src=\"./assets/js/owl.carousel.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/slick.min.js\"></script>\n");
      out.write("\n");
      out.write("        <!--wow, Animated-HeadLin, Mobile Menu -->\n");
      out.write("        <script src=\"./assets/js/wow.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/animated.headline.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.magnific-popup.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.slicknav.min.js\"></script>\n");
      out.write("\n");
      out.write("        <!-- Date Picker,Nice-select, sticky ,count-Down-->\n");
      out.write("        <script src=\"./assets/js/gijgo.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.nice-select.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.barfiller.js\"></script>\n");
      out.write("        <script src=\"./assets/js/countdown.min.js\"></script>\n");
      out.write("\n");
      out.write("        <!-- contact js -->\n");
      out.write("        <script src=\"./assets/js/contact.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.form.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.validate.min.js\"></script>\n");
      out.write("        <script src=\"./assets/js/mail-script.js\"></script>\n");
      out.write("        <script src=\"./assets/js/jquery.ajaxchimp.min.js\"></script>\n");
      out.write("\n");
      out.write("        <!-- Jquery Plugins, main Jquery -->	\n");
      out.write("        <script src=\"./assets/js/plugins.js\"></script>\n");
      out.write("        <script src=\"./assets/js/main.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
