/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-08-11 01:46:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class recuperarClave_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/Componentes/head.jsp", Long.valueOf(1628614301253L));
    _jspx_dependants.put("/Componentes/mensajesRespuesta.jsp", Long.valueOf(1628614301263L));
    _jspx_dependants.put("/Componentes/scripts.jsp", Long.valueOf(1628614301265L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\n");
      out.write("<head>\n");
      out.write("    \n");
      out.write("    <title> Recuperar Clave</title>\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"manifest\" href=\"site.webmanifest\">\n");
      out.write("        <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/slicknav.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/progressbar_barfiller.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/gijgo.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/animate.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/animated-headline.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/fontawesome-all.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/slick.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/style.css\">");
      out.write("\n");
      out.write("  \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- ? Preloader Start -->\n");
      out.write("    <div id=\"preloader-active\">\n");
      out.write("        <div class=\"preloader d-flex align-items-center justify-content-center\">\n");
      out.write("            <div class=\"preloader-inner position-relative\">\n");
      out.write("                <div class=\"preloader-circle\"></div>\n");
      out.write("                <div class=\"preloader-img pere-text\">\n");
      out.write("                    <img src=\"assets/img/logo/loder.png\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Preloader Start-->\n");
      out.write("\n");
      out.write("\n");
      out.write("    <main class=\"login-body\" data-vide-bg=\"assets/img/login-bg.mp4\">\n");
      out.write("        <!-- Login Admin -->\n");
      out.write("        \n");
      out.write("       \n");
      out.write("        <form class=\"form-default\" action=\"Mensajes\" method=\"POST\">\n");
      out.write("            \n");
      out.write("            <div class=\"login-form\">\n");
      out.write("                <!-- logo-login -->\n");
      out.write("                <div class=\"logo-login\">\n");
      out.write("                    <a href=\"index.html\"><img src=\"assets/img/logo/loder.png\" alt=\"\"></a>\n");
      out.write("                </div>\n");
      out.write("                <h2>Recuperar clave </h2>\n");
      out.write("                <div class=\"form-input\">\n");
      out.write("                    <label for=\"name\">Correo</label>\n");
      out.write("                    <input  type=\"text\" name=\"receptor\" placeholder=\"escriba su correo\" required>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-input pt-30\">\n");
      out.write("                    <input type=\"submit\" name=\"submit\" value=\"Recuperar Clave\">\n");
      out.write("                    <input type=\"hidden\" value=\"3\" name=\"opcion\">\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- Forget Password -->\n");
      out.write("                <a href=\"login.jsp\" class=\"forget\">login</a>\n");
      out.write("               <div class=\"container\">\n");
      out.write("            <h1> ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div style=\"color: #007180;\">\n");
      out.write("                        ");

                            if (request.getAttribute("mensajeError") != null) {
                        
      out.write("\n");
      out.write("                        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mensajeError}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                        ");
} else {
      out.write("\n");
      out.write("                        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mensajeExito}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                        ");
}
      out.write("\n");
      out.write("                    </div>\n");
      out.write("</h1>\n");
      out.write("        </div>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("        \n");
      out.write("        <!-- /end login form -->\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"./assets/js/vendor/modernizr-3.5.0.min.js\"></script>\n");
      out.write("<script src=\"./assets/js/vendor/jquery-1.12.4.min.js\"></script>\n");
      out.write("<script src=\"./assets/js/popper.min.js\"></script>\n");
      out.write("<script src=\"./assets/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Jquery Slick , Owl-Carousel Plugins -->\n");
      out.write("<script src=\"./assets/js/owl.carousel.min.js\"></script>\n");
      out.write("<script src=\"./assets/js/slick.min.js\"></script>\n");
      out.write("\n");
      out.write("<!--wow, Animated-HeadLin, Mobile Menu -->\n");
      out.write("<script src=\"./assets/js/wow.min.js\"></script>\n");
      out.write("<script src=\"./assets/js/animated.headline.js\"></script>\n");
      out.write("<script src=\"./assets/js/jquery.magnific-popup.js\"></script>\n");
      out.write("<script src=\"./assets/js/jquery.slicknav.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Date Picker,Nice-select, sticky ,count-Down-->\n");
      out.write("<script src=\"./assets/js/gijgo.min.js\"></script>\n");
      out.write("<script src=\"./assets/js/jquery.nice-select.min.js\"></script>\n");
      out.write("<script src=\"./assets/js/jquery.barfiller.js\"></script>\n");
      out.write("<script src=\"./assets/js/countdown.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- contact js -->\n");
      out.write("<script src=\"./assets/js/contact.js\"></script>\n");
      out.write("<script src=\"./assets/js/jquery.form.js\"></script>\n");
      out.write("<script src=\"./assets/js/jquery.validate.min.js\"></script>\n");
      out.write("<script src=\"./assets/js/mail-script.js\"></script>\n");
      out.write("<script src=\"./assets/js/jquery.ajaxchimp.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Jquery Plugins, main Jquery -->	\n");
      out.write("<script src=\"./assets/js/plugins.js\"></script>\n");
      out.write("<script src=\"./assets/js/main.js\"></script>");
      out.write("\n");
      out.write("    \n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
